### ISSUE TITLE
JS adds inline border styles to dropdown

### ISSUE THREAD

**Issue by darrenbarklie** [niftit/ppfa-ui#1]
![ppfa-ui-inline-styles](https://cloud.githubusercontent.com/assets/3026261/8591695/4100950e-2654-11e5-9a96-465e0edd69b8.png)

**Comment by thanhthao993** [comment]
@darrenbarklie  I try to add border styles for div but it working incorrect.
I removed it and added border style for button
I pushed to GitHub. Please review it. Thanks Daz
