### ISSUE TITLE
Large input element

### ISSUE THREAD

**Issue by anhhaoha** [niftit/ppfa-ui#6]
Height of input should be set default height.
![input_large1](https://cloud.githubusercontent.com/assets/8373177/12138868/b223cf4e-b48e-11e5-9eb3-7f8d5d3ed687.png)

![input_large2](https://cloud.githubusercontent.com/assets/8373177/12138945/54e5f14e-b48f-11e5-9376-56df884d8cd6.png)

**Comment by thanhthao993** [comment]
Add class for input 
![untitled](https://cloud.githubusercontent.com/assets/10804177/12139520/9ff86b72-b493-11e5-89ea-82b253c364ed.png)

**Comment by darrenbarklie** [comment]
Please update on status when applied.  Thanks.  :)

**Comment by nguyenhoangnamkg** [comment]
@anhhaoha Please recheck

**Comment by anhhaoha** [comment]
look good. Closing issue
